apiVersion: v1
kind: Service
metadata:
  name: hms-service
  namespace: dev

  labels:
    service: hms
spec:
  selector:
    app: hms-development-sys
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 9000
