apiVersion: v1
kind: Service
metadata:
  name: hms-sys-service
  # namespace: dev

  labels:
    # service: hms
    service: hms-development-sys
spec:
  selector:
    app: hms-development-sys
  type: NodePort
  ports:
    - port: 9000
  # ports:
  #   - protocol: TCP
  #     port: 9000
  #     targetPort: 9000
